--- # h2 for local
spring:
  config:
    activate:
      on-profile: "h2"

  jpa:
#    defer-datasource-initialization: true

    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create

#  sql:
#    init:
#      mode: always

  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

--- # mysql for dev prod
spring:
  config:
    activate:
      on-profile: "mysql"

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: never

  datasource:
    url: jdbc:mysql://matchup.cnaaj7y3vcgh.ap-northeast-2.rds.amazonaws.com:3306/matchup?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: matchup_admin
    password: matchup!
    driver-class-name: com.mysql.cj.jdbc.Driver

--- # h2-in-memory
spring:
  config:
    activate:
      on-profile: "h2-in-memory"

  jpa:
#    defer-datasource-initialization: true

    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create

#  sql:
#    init:
#      mode: always

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true