spring:
  profiles:
    active:
      - local

    group:
      local:
        - db
        - oauth
        - h2
        - oauth-local
      dev:
        - db
        - oauth
        - oauth-dev
#        - h2-in-memory
        - mysql
  # 파일업로드 최대 용량 설정
  servlet:
    multipart:
      maxFileSize: 1MB
      maxRequestSize: 1MB
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 클라우드 설정
cloud:
  aws:
    s3:
      bucket: match-up-142023
    credentials:
      access-key: AKIAUQRV7XQ4426BN742
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false