spring:
    profiles:
        active: local

        group:
          local:
              - db-local
              - oauth-local
          dev:
              - db-dev
              - oauth-dev
        include:
            - oauth
            - db

    h2:
        console:
            enabled: true

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace