spring:
    profiles:
        active:
            - local

        group:
          local:
              - db
              - oauth
              - h2
              - oauth-local
          dev:
              - db
              - oauth
              - oauth-dev
              - mysql

logging:
    file:
        name: /var/log/spring/spring.log

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace