spring:
  profiles:
    active:
      - local
    group:
      local:
        - db
        - oauth
        - h2
        - oauth-local
      dev:
        - db
        - oauth
        - oauth-dev
        - mysql

      test:
        - db
        - oauth
        - h2-in-memory
        - oauth-local
  config:
    import: optional:file:.env[.yml]

  # 파일업로드 최대 용량 설정
  servlet:
    multipart:
      maxFileSize: 1MB
      maxRequestSize: 1MB
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 클라우드 설정
cloud:
  aws:
    #DynamoDB 설정
    access-key: AKIAUQRV7XQ4Q4EUNLEB
    secret-key: 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

    s3:
      bucket: match-up-142023
    credentials:
      access-key: AKIAUQRV7XQ4426BN742
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

sentry:
  dsn: https://a3a01f3fc21322c893e8082cccb738d9@o4505941819457536.ingest.sentry.io/4506139775205376
  traces-sample-rate: 1.0
  send-default-pii: true
  logging:
    enabled: true
    minimum-event-level: WARN
    minimum-breadcrumb-level: WARN