spring:
    profiles:
        active:
            - local
            - blue

        group:
          local:
              - db-local
              - oauth-local
          dev:
              - db-dev
              - oauth-dev
              - blue-green-dev
        include:
            - oauth
            - db
            - blue-green

    h2:
        console:
            enabled: true

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace