--- # h2 for local
spring:
  config:
    activate:
      on-profile: "h2"

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: embedded

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true

  properties:
    hibernate:
      format_sql: true

--- # mysql for dev prod
spring:
  config:
    activate:
      on-profile: "mysql"

  jpa:
    hibernate:
      ddl-auto: update