--- # h2 for local
spring:
  config:
    activate:
      on-profile: "h2"

  jpa:
    defer-datasource-initialization: true

    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

--- # mysql for dev prod
spring:
  config:
    activate:
      on-profile: "mysql"

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://mysql:3306/matchup?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

--- # h2-in-memory
spring:
  config:
    activate:
      on-profile: "h2-in-memory"

  jpa:
    defer-datasource-initialization: true

    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

# todo: web-allow-others: true 나중에 지우자
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true