spring:
  profiles:
    active:
      - local
    group:
      local:
        - db
        - oauth
        - h2
        - oauth-local
      dev:
        - db
        - oauth
        - oauth-dev
        - mysql

      test:
        - db
        - oauth
        - h2-in-memory
        - oauth-local
  config:
    import: optional:file:.env[.yml]

  # 파일업로드 최대 용량 설정
  servlet:
    multipart:
      maxFileSize: 1MB
      maxRequestSize: 1MB
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 클라우드 설정
cloud:
  aws:
    #DynamoDB 설정
    access-key: AKIAUQRV7XQ4V2BJ5M4Q
    secret-key: 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

    s3:
      bucket: match-up-142023
    credentials:
      access-key: AKIAUQRV7XQ4YJHCRANF
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

sentry:
  dsn: https://13f7b7402d176d856e4ea628df788a4a@o4506213122965504.ingest.sentry.io/4506213124145152
  traces-sample-rate: 1.0
  send-default-pii: true
  logging:
    enabled: true
    minimum-event-level: WARN
    minimum-breadcrumb-level: WARN
  environment: production

