spring:
  jpa:
    hibernate:
      ddl-auto: create # 배포 할땐 최소 validation
    properties:
      hibernate:
        format_sql: true

--- # local env
spring:
  config:
    activate:
      on-profile: "db-local"

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true

--- # dev env
spring:
  config:
    activate:
      on-profile: "db-dev"

  jpa:
    hibernate:
      ddl-auto: update