spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 675474494307-naneckvcdelshfnd42392f9qalj4uhbq.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile

          naver:
            client-id: 8P36eHkHT1NBb7vuiEf6
            client-secret: IGJt1zPOQ9
            redirect-uri: http://match-up.xyz/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: naver

          kakao:
            client-id: 31c6580ccbfd7c1b4eb313d5cf759dcc
            client-secret: GKZ6sn8Qtl7sGhlxH2d2BPLXfseu4xN7
            redirect-uri: http://match-up.xyz/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# JWT config
jwt:
  issuer: match-up.xyz
  secret_key: ASAasidufhASKHFUfH234356098273aSDfSEDF

--- # local env: localhost:5173 redirect
spring:
  config:
    activate:
      on-profile: "oauth-local"

  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

# oauth2 login url
oauth2:
  logout_success_url: http://localhost:5173/logout/token
  success_url: http://localhost:5173/login/token

--- # dev env: match-up.xyz redirect
spring:
  config:
    activate:
      on-profile: "oauth-dev"

# oauth2 login url
oauth2:
  logout_success_url: https://match-up.xyz/logout/token
  success_url: https://match-up.xyz/login/token

--- # local test in docker container
spring:
  config:
    activate:
      on-profile: "local_test"

# oauth2 login url
oauth2:
  logout_success_url: http://localhost/logout/token
  success_url: http://localhost/login/token