spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 675474494307-naneckvcdelshfnd42392f9qalj4uhbq.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile

          naver:
            client-id: 8P36eHkHT1NBb7vuiEf6
            client-secret: 2dWps2Df3V
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          github:
            client-id: 36c02e4d59269445d0dc
            client-secret: 41942a09f0d5ee0653e4e0da64180859c228d588

          kakao:
            client-id: 499e70f5f21e7f5ed9065449c5738c9e
            client-secret: WhCn5PoVSJn4UOs5oHZmUBVAJinfLXPa
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id